### ISSUE TITLE
LAHI integration release

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/integration-service#106]
## Requirements from customer
     Sync start date 

## Steps:
 - Deploy latest integration code to prod int server
 - Ensure that GCP credentials file is copied correctly and the env variables for LAHI are also set correctly
 - Take the integration bundle from Staging LAHIINT UAT and apply to Prod
     - Login Staging: https://int-staging.avniproject.org:443/int/login
     **- Ensure that the user is configured to use LAHI integration-system**
     - Export bundle : https://int-staging.avniproject.org:443/int/export 
      - Logout: https://int-{env}.avniproject.org:443/int/logout
     - Login Prod: https://int-prod.avniproject.org:443/int/login
     **- Ensure that the user is configured to use LAHI integration-system**
     - Import bundle: https://int-prod.avniproject.org:443/int/import [formData: "bundleZip" => bundleZipFile.zip]
 - Setup Integration system Monitoring and alert. Configure Errors / Exceptions to be ignored
 - After the first complete run, disable the errors that will happen due to old mappings. See error examples
 - Uploaded prod org bundle to lahi-int org
 - Uploaded lahi-int org bundle to prod org
 - then triggered sync of Lahi integration module from 01 Jan 2024
 

# Acceptance criteria

Completed Students registerations on Glific using RegisterMe flow should be successfully synced to Avni LAHI prod organisation using Prod Integration-service once every hour of every day.

# Error examples.
Answer mapping not found for coded concept avni_academic_year answer field: 2022
Answer mapping not found for coded concept avni_stream answer field: Science

**Comment by himeshr** [comment]
Lahi integration synced a test student to prod organisation.
https://app.avniproject.org/#/app/subject?uuid=6aa64d7b-3e4e-4519-8209-32411fb7ee3b
