### ISSUE TITLE
Dates mismatch between Avni and Bahmni

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/integration-service#110]
https://avni.freshdesk.com/a/tickets/2340

Looks like the issue is because of date formats mismatch. We store the dates in UTC format and convert it to UTC+5:30 before rendering in our website and mobile app. But during sync looks like we have not made the conversion.

**Comment by petmongrels** [comment]
the code for this is not integration service. lets take it out of our wall.

**Comment by mahalakshme** [comment]
@petmongrels what to do for the associated ticket?

**Comment by himeshr** [comment]
This was the case for Goonj as well, we have introduced conversion logic wherever needed as part of GoonjRepositories in integra.
If the core date storage format returned by the API is changed as part of this ticket, then we would need to remove the conversion logics within GoonjRepositories.

**Comment by mahalakshme** [comment]
duplicate so closing.
