### ISSUE TITLE
LAHI Integration failing after v6.1.0 release on prod

### ISSUE THREAD

**Issue by himeshr** [avniproject/integration-service#116]
LAHI Integration failing after v6.1.0 release on prod. Related error logs are available in attachment.

[LAHI_integration_job_error_logs.txt](https://github.com/avniproject/integration-service/files/14009399/LAHI_integration_job_error_logs.txt)

**Comment by petmongrels** [comment]
https://github.com/avniproject/avni-server/commit/19f0133e8ddc0e75438503cffada2f4a5320319c

**Comment by himeshr** [comment]
Lahi Prod integration is working fine now.
