### ISSUE TITLE
Change in integration service to use new API

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/integration-service#117]
https://avni.freshdesk.com/a/tickets/2340

### Acceptance criteria:
- Make necessary change in integration service to avoid the date issue raised in the ticket, by using the API version 2 as mentioned [here](https://avni.freshdesk.com/a/tickets/2340) when retrieving observations
- Looks like to achieve the above some code under bahmni folder needs to be fixed.

**Comment by petmongrels** [comment]
QA will be done by Kannan (customer)

**Comment by mahalakshme** [comment]
have asked kannan for the status
