### ISSUE TITLE
Goonj documentation and context sharing

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/integration-service#119]
### Need:
- To be able to efficiently handle work from the org in focus.

### Acceptance criteria:
- Others in implementation and product team also be able to solve tickets
- Others in product team also be able to do integration work
- Setup call and add documentation as necessary. Related documentation card: https://github.com/avniproject/integration-service/issues/81

**Comment by himeshr** [comment]
Work output documentation file is available [here](https://docs.google.com/document/d/1wkvdS5abbgfmQ8uUOoxBaIarBJdxq4UEoZOrr6aghas/edit?usp=sharing)

**Comment by himeshr** [comment]
Duplicate of #81
