### ISSUE TITLE
Goonj - Changes to API

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/integration-service#121]
There have been the following changes made in the Goonj implementation - https://github.com/avniproject/Goonj/issues/88 in ```Goonj Revamp UAT``` org
Corresponding changes have also been made to the SalesForce API. The purpose of this card is to make necessary changes in the integration-service in order to get integration to work. 

The purpose of this story is to make corresponding changes in the integration

### Pre-requisite
Salesforce has completed the changes before the new Integration-service changes are deployed 

### Changes in scope
- (Testing only) - Change in activity type/subtype/category and measurement type as mentioned in https://docs.google.com/spreadsheets/d/1Hz6frFs1Nj9YPE2ia1E2XlWSIIn_2iVG6GYbnO2tUgE/edit?usp=sharing 
- Distributions form 
  - Add fields DisclaimerPhotographs, ReceiverListPhotographs, TotalNumberOfReceivers, 
  - Change typeOfCommunity to semicolon separated items since it is now a multiselect (To ensure backwards compatibility, which adds a check for this observation's value and converts single value to array of length one)
  - Remove numberOfDistributions
- DispatchReceipt
  - Add Remarks
- Activity
  - Add WasDisclaimerFormFilled (values Yes and No)
  - Add FormCrossChecked (values Yes and No)
  - Change objectiveOfCFWwork to semicolon separated items since it is now a multiselect (For backwards compatibility, we need to create a new concept and add it to the form. On integration service, the values will be picked up from both these concepts)

### Testing
- New changes work
- Any existing forms work (backwards compatibility when we go live)

**Comment by vedfordev** [comment]
@vinayvenu Can u check we added total number of receiver in Inventory details section. In Reached to details section also have total number of receiver which is used by ** TotalNumberOfReceivers** .
