### ISSUE TITLE
Avoid sending out repeated Goonj Up and Down healthcheck emails

### ISSUE THREAD

**Issue by himeshr** [avniproject/integration-service#123]
Avoid sending out repeated Goonj Up and Down healthcheck emails. This happens mostly during the AvniGoonjMainJob run after the AvniFullErrorJob. 
We might have to reset the counts after the AvniFullErrorJob without sending the healthchecks during the ErrorJob.

**Comment by vinayvenu** [comment]
Commit https://github.com/avniproject/integration-service/commit/ecf67c35a953d80a8f8cb4a8e479a3c73b44f759
