### ISSUE TITLE
Synchronise Activity from Avni to SF

### ISSUE THREAD

**Issue by himeshr** [avniproject/integration-service#20]
- The Activity encounter should be Synced to SF using corresponding Demand **Or** Distribution with appropriate - voiding status, last modified date time, and sourceId. For the remaining fields use the mapping metadata approach.
- Save error record for missing mapping for a field, its coded answers, or missing Activity in Avni.
- The sync should resume from the previous point if an uncaught exception occurs.
- Make it ready for QA
- Deploy to Staging

**Comment by AchalaBelokar** [comment]
Integration is not working for 
Activity Type: Agriculture Plantation 
Activity  Subtype: Compost pit 
Activity Category: Repairing
