### ISSUE TITLE
Synchronize Distribution from Avni to SF

### ISSUE THREAD

**Issue by himeshr** [avniproject/integration-service#21]
- The Distribution encounter should be Synced to SF using corresponding DispatchStatus with appropriate RecordType and DistributionLines - voiding status, last modified date time, and sourceId. For the remaining fields use the mapping metadata approach.
- Save error record for missing mapping for a field, its coded answers, or missing Distribution in Avni.
- The sync should resume from the previous point if an uncaught exception occurs.
- Make it ready for QA
- Deploy to Staging

**Comment by AchalaBelokar** [comment]
The type of initiative rule is not working for Only Rahat and DFW-Rahat
