### ISSUE TITLE
Handle Deletion of Avni Source entities in Salesforce

### ISSUE THREAD

**Issue by himeshr** [avniproject/integration-service#25]
Currently we only create or update Avi source Goonj Enitities, DispatchReceipt, Distribution and Activity in Salesforce.
We would need to include "isVoided" field as part of Post Request for those EntityTypes or invoke a separate Deletion API, as per Salesforce design.

Acceptance Criteria:
.* We should be able to delete Goonj Enitities DispatchReceipt, Distribution and Activity in Salesforce if they have been voided in Avni.
.* Handle Deletion errors

**Comment by vinayvenu** [comment]
We will deal with this after the new API comes out.
