### ISSUE TITLE
Deploy to prod

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/integration-service#28]
### Acceptance criteria
- Prod deployment of integration-service and integration-webapp
- DNS setup
- Log rotation
- Scheduling of jobs for Goonj
- Increase size of ETL machine, deploy there //Not to be done, instead deployed on separate server

**Comment by himeshr** [comment]
Setup integration:
==================
*. DNS setup //Done
*. Increase size of ETL machine //done create a new small machine with ubuntu os
*. Created launch template //Done
*. Create avni-int db in prod //Done
*. integration DB migrate from staging to prod //Done
*. Reset sync timestamps and clear errorRecords and errorRecordLogs //Done
*. setup prod server etl ssh config connection //Done

*. build apps (int backend and fontend) //Done
*. Create prod-vars //Done
*. change vars.yml to move out app_url: "int-staging.avniproject.org" to staging //Done
*. create prod-secret-vars //Done
*. create onpremise_integration_servers.yml for prod deploy //Done
*. Trigger int-server setup and apps deploy //Done
*. User login issue //Done, created a bug in avni-server project to delete tasks entities data on orgDataDelete
*. com.amazonaws.services.cognitoidp.model.UserNotFoundException: User does not exist. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: UserNotFoundException; Request ID: 252483f>//pending
*. config logs rolling //Done
*. Tweaks to goonj and power uat config, lower frequency  //Done
