### ISSUE TITLE
Happy path integration with Exotel

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/integration-service#32]
### API Details
- Avni API - POST /api/task
- Exotel API - https://developer.exotel.com/api-console/make-a-call-api#BulkCallDetails

### Tasks
- Setup a gradle module for power
- DB Migration for the module to setup the metadata
- Improve our background scheduler to run integration of multiple projects
- Migrate data from Exotel to @powertest organisation in staging
- Perform mapping
- Handle errors

#### Field Mapping
- Map Task type - "Call"
- Map Task name - "Call"
- Map Task status to "New"
- Map field "To" to "State" and "Program" for the metadata of the task as below
  - 011-41136600 -> State-Delhi, Program-BoCW
  - 011-41132680 -> State-Delhi, Program-RTE
  - 011-41132689 -> State-CG, Program-RTE
- Field "From" should be mapped to "Number"

**Comment by vinayvenu** [comment]
Question
1. When we go live, is there a date on which we can switch per number?

**Comment by AchalaBelokar** [comment]
1) I called this no 011-41132689 -> State-CG, Program-RTE from 8668379159 at 8.37 am but still this no is not appearing in the assignment task.
2) 011-41136600 -> State-Delhi, Program-BoCW I am trying to call this no but not able to connect this no.

**Comment by vindeolal** [comment]
@AchalaBelokar 
This is fixed now, can you please test it now.
