### ISSUE TITLE
Metadata migration

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/integration-service#34]
### Acceptance criteria

There are mechanisms to automate pulling of metadata for an organisation on integration-service. and pushing them to another organisation/implementation. This will be used to migrate changes from one organisation to another

### Tech notes
- Start using uuids

**Comment by petmongrels** [comment]
For Exotel integration, all of the data is set up in the migration script. So this story can be played later.

**Comment by himeshr** [comment]
Closed as duplicate of #73
