### ISSUE TITLE
Deploy and define systemctl service for running the integrator service

### ISSUE THREAD

**Issue by petmongrels** [avniproject/integration-service#4]
Some helpful scripts can be found here for defining the systemctl service in CentOS. We can use these or do it from scratch - depending on how we want to do it.

https://github.com/avniproject/avni-integrator-host

Acceptance Criteria
----------
1. Integrator service is running in production and/or staging environment.
2. There is an automated way to deploying the new build to the same server

**Comment by petmongrels** [comment]
Discuss
1. Should we have a separate env for staging and for production?
2. RPM, Jar, CI process

**Comment by himeshr** [comment]
> 

*) For "Should we have a separate env for staging and for production?", we'll have them separate and Avni-int will join Goonj-SF-UAT. We'll have separate JVM for Avni-int. Set it up a service (systemctl)
*) Make avni-int route requests to static react app
*) Make use of CI process for build and deploy as a jar
Good to have:
---------------
*) Use https://github.com/SamanvayOrg/budget-planner-infra as reference to setup avni-int service on a node

**Comment by himeshr** [comment]
*) Integration-service will also service static pages 
*) we'll deploy the avni-integration-service and integration-admin-app similar to the way avni-server and avni-webapp are deployed today
*) we'll use CI-Circle for Build and deploy of the avni-integration-service and integration-admin-app
*) We'll use separate JVM to run avni-integration-service
