### ISSUE TITLE
POST dispatch receipt API

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/integration-service#54]
### Context
Dispatch receipt is created in Avni as an Encounter

**Comment by Dinesh2019** [comment]
We have the dependencies from the sales force team.
When we create the dispatch receipt from avni we unable to validate from the salesforce:
Avni Screenshot :
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/895b4b03-f0c4-43d9-a280-90cdfa59e2b0)
Sales force screenshot : 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/01c938f4-36e0-4641-8aad-43f2b4cfa438)
goonj document:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/1ed35202-6ce4-4fd0-8a34-adc851947b18)

**Comment by Dinesh2019** [comment]
Dispatch receipt is not reflecting in the sales force.
Screenshot form avni:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/dc538d7f-9c4b-46cf-81ca-d2eb55d21219)
Screenshot from sales force:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/21576090-404b-4ed2-95de-7fc6f5a1f2cb)

**Comment by Dinesh2019** [comment]
dispatch is not reflecting in both avni web app and mobile app
