### ISSUE TITLE
Handle null values for address fields in Implementation Inventory GET API response

### ISSUE THREAD

**Issue by himeshr** [avniproject/integration-service#78]
Vinay found 365 entries of ImplementationInventory..  where address_id field is null.
Its caused by following fields coming as null in the Goonj Salesforce "Get ImplementationInventories" API:
            "CenterFieldOfficeState": null,
            "CenterFieldOfficeDistrict": null,

### Tasks:
 - We need to handle Null values for address fields in all Goonj entities synced from Goonj Salesforce to Avni.
 - Void all existing ImplementationInventory with addressIds null in DB (Post deploy of above fix)

Code place:
-----------
Subject.java:
    public void setAddress(String address) {
        map.put(AddressFieldName, address);
    }

**Comment by himeshr** [comment]
This bug has been fixed in Salesforce. ImplementationInventory wont send null values anymore.

**Comment by ashusvnath** [comment]
@himeshr : How many records are updated by the script you provided in the comment ?  Are all the 365 entries fixed ?
