### ISSUE TITLE
Add Readme Documentation on Avni-Goonj Integration

### ISSUE THREAD

**Issue by himeshr** [avniproject/integration-service#81]
## Tasks:
0. General information about integration-service Design:
 - Why mappings are required in integration service? / Why can’t system identify on itself
 - what happens when integration service encounters an error, stops or continue? Is this behaviour different across integrations?
 - How fresh records sync in integration service works.?
 - How error processing happens.?
 - How frequently the service runs - Is it configurable?
1. Add Readme Documentation to give basic intrdouction on Avni-Goonj Integration.
    -  Goonj
    -  Current System Using Papers and forms
    - Challenges with old system
    - Why use Avni
    -  Various subject and encounter types
    - Source locations and sync frequency and constraints
    - Integration config
    - Challenges faced with integration work (Locations, Mapping, forms reconfiguration)
    - Major Avni functionalities used in this integration
    - Mapping metadata, groups and types and the logic used for transformation of data between the 2 systems
    - Different entity sync pipelines
    - Direct updates done by Salesforce on Avni
    - Health Checks and Error Record Reports
    - Recovery from errors
    - Sync frequency (main and error jobs)
    - Future scale and growth opportunities (Filter and fetch by States / Accounts)

2. Add Readme Documentation on how to handle Errors in Avni-Goonj Integration.
    - Document error types managed by two parties, Party background intro, steps to resolve, etc.. in Readme

Google sheet link for ErrorTypes is available at https://docs.google.com/spreadsheets/d/1qw9DLEaBS7o0Svc0TYUztj8n6UjzO7iQTONDhbIbI44/edit?usp=sharing

3. Create solutions for handling Support for Goonj
4. Add guide on special functionalities to be validated during regression for Goonj
5. Add process to be followed by implementation team to develop on goonj organisation
6. Create guide to be used by Goonj team to understand Avni-Salesforce Integration error monitoring

**Comment by mahalakshme** [comment]
@himeshr I ve moved this to Ready. Let me know if you think otherwise. Want to do some documentation cards as part of every release.

**Comment by himeshr** [comment]
Work output documentation file is available [here](https://docs.google.com/document/d/1wkvdS5abbgfmQ8uUOoxBaIarBJdxq4UEoZOrr6aghas/edit?usp=sharing)

**Comment by himeshr** [comment]
No QA required for this.
