### ISSUE TITLE
Configuration init on all environments

### ISSUE THREAD

**Issue by vedfordev** [avniproject/integration-service#85]
## Acceptance criteria

 - Avni and Glific bigQuery credentials are configurable using env properties (not just in the application.properties file)
 - Lahi Integration sync frequency is also configurable using env properties.
 - All secrets are stored in avni-infra as encrypted values
 - Secrets are defined in avni-infra for staging (UAT) and production
 - See below for environment variable values (non-secrets)
 - The google application credentials file is deployed along with the app at /etc/avni_int_service/keys/google_lahi_bigquery_conf.json
 - Deployment using CI works fine without any manual intervention

Configuration for UAT user

```
export LAHI_GLIFIC_GCP_PROJECT_ID="glific-lms-lahi"
export LAHI_GLIFIC_GCP_DATASET_NAME="918956411022"
export LAHI_AVNI_API_USER="external-api-user@***"
export LAHI_AVNI_API_PASSWORD="***"
export LAHI_AVNI_API_URL="https://app.avniproject.org"
```

## Lahi Integration sync frequency Properties to init:
```
export LAHI_INT_SCHEDULE_CRON="0 0/5 * * * ?"
export LAHI_INT_SCHEDULE_CRON_FULL_ERROR="0 2 0/6 * * ?"
export GOOGLE_APPLICATION_CREDENTIALS="(filepath)"
```

**Comment by vinayvenu** [comment]
@1t5j0y had changed google application credentials to GLIFIC_GCP_CREDENTIALS_FILE. It will pick up classpath:gcp.json if this is not available and override GOOGLE_APPLICATION_CREDENTIALS

**Comment by 1t5j0y** [comment]
Thanks @vinayvenu . Updated infra scripts to set `GLIFIC_GCP_CREDENTIALS_FILE`

**Comment by petmongrels** [comment]
reviewed code as part of another story development

**Comment by himeshr** [comment]
The config values set for the gcp credentials json file for staging environment are not correct.
Integration-service app doesnot come up after doing a deployment.
To overcome this issue, 
 - i've temporarily disable deploy of a new lahi-gcp-credentials json file as part of every deploy (git commit 8d244788551b415bc2a3aa8001d1c0d209938030)
 - Copied a valid copy of lahi-gcp-credentials json file to staging-int-server

After fixing this issue for all environments, undo the changes done in commit (8d244788551b415bc2a3aa8001d1c0d209938030)

**Comment by mahalakshme** [comment]
@1t5j0y also https://app.circleci.com/pipelines/github/avniproject/avni-etl/228/workflows/516e653f-bf22-4e66-b12f-d65056320716/jobs/813 is failing  because of the changes made as part of this card. the role appserver is used by etl as well. So changed made to this role for integration server is failing the pipeline. Commit: 290eaaf6 in avni-infra codebase.

**Comment by 1t5j0y** [comment]
@mahalakshme already pushed a fix to remove this impact to non integration repos.

**Comment by 1t5j0y** [comment]
@himeshr fixed for staging. Let me know if we have details for other environments as well and can add them if we do. If not, can add the variables when we move to a different environment.

**Comment by himeshr** [comment]
@1t5j0y The staging changes look good.
The values for prod would be same as specified for staging.
It isn't required for any other environment(other than prod and staging)

**Comment by himeshr** [comment]
@1t5j0y done with adding the lahi gcp config for prod as well.
Moving to QA_ready

**Comment by AchalaBelokar** [comment]
https://docs.google.com/spreadsheets/d/191uuBE2R9Q8U0WKfBDsfECX0OiI0zXHpjkBxiZPeK58/edit#gid=346525539
