### ISSUE TITLE
Set up Avni-client and session for LAHI org

### ISSUE THREAD

**Issue by himeshr** [avniproject/integration-service#86]
Set up Avni-client and session for LAHI org
 - Create API User
 - Grant required privileges
 - Configure, URL, username, password in LAHI module
 - Setup method to perform create based on bulk fetch of registrations from Glific
 - Setup method to perform create for errored registration
 - During Student create, if entity already exists, skip updating the entity (LAHI requirement)

**Comment by vedfordev** [comment]
## Developer's Note :

**Org :** vedantbootcamp 

I have tried with dummy doctor data and tried to create record in mentioned org.
