### ISSUE TITLE
Error retries for student sync

### ISSUE THREAD

**Issue by himeshr** [avniproject/integration-service#89]
### Acceptance criteria

- If a student sync fails, then it is retried in the ErrorSync flow with the student information fetched using the BQ query given below so that latest information of the student is available to try the sync once again

 ```
select c.phone, fr.results, s.inserted_at
from `glific-lms-lahi.918956411022.contacts` c, UNNEST(c.fields) AS s
join `glific-lms-lahi.918956411022.flow_results` fr 
on fr.contact_phone = c.phone 
WHERE
(s.label, s.value) = ('avni_reg_complete', 'Yes')
AND
fr.name = 'Avni Students Registrations Flow'
AND 
fr.id = <flowResultId>
order by s.inserted_at desc
limit 1

```

- On Platform errors, prevent the LAHI module from continuing with processing of records.

**Comment by petmongrels** [comment]
we can do this bit later. after UAT is complete

**Comment by mahalakshme** [comment]
@vinayvenu u r reviewing this?

**Comment by AchalaBelokar** [comment]
After reset the password the error log is not coming

**Comment by petmongrels** [comment]
For such errors the integration process will stop precessing of all
messages. By design
